### ISSUE TITLE
error in line 9 when trying to import the <module>

### ISSUE THREAD

**Issue by giuliomagnifico** [runezor/PiArtFrame#1]
Hi, and thanks for the cool script!

I've bought all you wrote and I'm with the same Waveshare 7.5" e-ink panel, I also installed it following the guide on the Waveshare website, all is working, the Waveshare demo is working of course (please ignore my working environment 😁)

![IMG_0544](https://github.com/runezor/PiArtFrame/assets/1975176/4f44a258-d247-4661-9ec0-4f51155ee014)

but if I launch your script I get the following error:

```
root@DietPi:~/PiArtFrame# python3 main.py
Traceback (most recent call last):
  File "/root/PiArtFrame/main.py", line 9, in <module>
    from waveshare_epd import epd7in5_V2
ModuleNotFoundError: No module named 'waveshare_epd'
root@DietPi:~/PiArtFrame#
```
The only difference is that I had to install the module via apt instead of pip (because of the update), I mean I had to use these commands:

```
apt install python3-RPi.GPIO
apt install python3-spidev
```

The module name should be the same/correct because is the correct name, also when I launch the demo I use the command: `python3 epd_7in5_V2_test.py` and it woks.

Unfortunately I don't know anything about python, any help is appreciate.

Thanks and best regards

**Comment by karlmose** [comment]
Hey!

You may just need a bit of path wrangling...

Did you clone this repo? https://github.com/waveshareteam/e-Paper/

If so, try copying the folder waveshare_epd folder (found at e-Paper/RaspberryPi_JetsonNano/python/lib/) into the same folder as this project, ie. the project root folder, and try running it again. Let me know if this works!

At some point I'll get around to making the setup a bit easier, but this is just a side project for me so some of the setup is a bit hacky.

**Comment by giuliomagnifico** [comment]
Yes it worked!

![IMG_0551](https://github.com/runezor/PiArtFrame/assets/1975176/cd7b0196-bc62-42ee-9321-ee7b8050a481)

Your instructions for the setup are pretty easy, if I have time I will write something more detailed (and easier) giving to credits of course.

For load it boot now I'm trying to use _crontab_ as simply as

`@reboot bash -c 'cd /root/PiArtFrame && /usr/bin/python3 main.py'`

and it should work. 

If you don't mind I'll give a look to the script to check if I can customize something.

**Comment by karlmose** [comment]
Looks great! Glad you got it sorted!

Quite need to see another one in the wild.

If you'd like to make any modifications to the README or the code itself feel free to make a pull request!
