### ISSUE TITLE
E-Ink Driver Install

### ISSUE THREAD

**Issue by robweber** [runezor/PiArtFrame#2]
Cool project - I found it on Reddit. You mentioned in the README that you'd be open to other ways to install the Waveshare driver. Wanted to throw out a shameless plug for a library I maintain called [omni-epd](https://github.com/robweber/omni-epd). A lot of other projects are utilizing it. It's a single library that pulls in support for all Waveshare displays in the repo you mentioned as well as Inky displays and the larger IT5981 displays. All the method calls are abstracted so in your project you just need a one-liner to import the correct display type and everything else just works. Much easier on the end user and your project can support most of the popular e-ink displays right out of the box. 

If you're interested integration is pretty simple, you probably only need to change a few lines of code. If you need help feel free to reach out.

**Comment by karlmose** [comment]
That does sound quite neat!

I'll try to look into this in the coming weeks. If you end up doing an implementation yourself in the meantime do feel free to make a pull request!

**Comment by karlmose** [comment]
Rob was kind enough to merge in his library. Closing this issue for now.
